[Lit] Implement a new __include directive, and sketch of a prologue. (#4876)
We'll eventually have a proper modular 'import' directive, but until
then we need to unblock progress.  Do this by adding a simple textual
__include directive that will allow us to get things going.

While simple, we do get nice diagnostics out of it, e.g. things like:

```
/Users/clattner/Projects/modular/KGEN/test/parse-lit/basic-lit.lit:158:1: error: invalid redefinition of "DType"
struct DType:
^
Included from /Users/clattner/Projects/modular/KGEN/test/parse-lit/basic-lit.lit:3:
/Users/clattner/Projects/modular/KGEN/test/parse-lit/../lit-examples/prolog.lit:5:1: note: previous definition here
struct DType:
^
```

MODULAR_ORIG_COMMIT_REV_ID: e0e18a1da60223a7e70618c928826216461576f8