Revert "[Kernels][graph-api] Expose SplitK Reduction Precision to Graph API (#54070)" (#54113)
This reverts commit e2841310b89b48c761e254ef06aa6a847c35b841.

PR #54070 caused all models in the `torch.compile` test suite to fail on
macOS (Apple Silicon) with the following error:
```
error: static assertion failed: non-exhaustive visitor!
              static_assert(false, "non-exhaustive visitor!");
```
MAX_INTEGRATION_TESTS_REV_ID: c015a13f11e8b77723785947c47199a5275c730b