[API] Improve error message for positional args to execute API (#21883)
Instead of the error messsage being
```
TypeError: execute() takes 1 positional argument but 2 were given
```

we now make it actionable by saying
```
Execute API only accepts key word arguments e.g. outs = model.execute(arg0=np.ones((1, 10)).astype(np.float32))
```

Fixes #15494

MAX_PYTHON_ORIG_REV_ID: 062ebc710f0a5ac3df2619268ce5f2e8f7e7abcb