[LLCL] Hide `Detail::addrToHex` implementation to avoid RTTI issues. (#25356)
The change avoids including "llvm/Support/Format.h" indirectly in
`TorchInterface` (which is built with RTTI enabled).

This fixes
```
/usr/bin/ld: PyTorch/lib/StockTorchInterface/CMakeFiles/StockTorchInterface.dir/TorchInterface.cpp.o:(.data.rel.ro._ZTIN4llvm13format_objectIJlEEE[_ZTIN4llvm13format_objectIJlEEE]+0x10): undefined reference to `typeinfo for llvm::format_object_base'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

MODULAR_ORIG_COMMIT_REV_ID: 152592997ee39d6045ec6819d7fa26a429f3b1e8