[Eagle] Pass attn metadata for draft1-K into graph instead of computing within
This is in preperation for device graph support

```
% HF_HUB_OFFLINE=0 br smoke-test -- nvidia/Kimi-K2.5-NVFP4__eagle --disable-timeouts
07:12:32.318 WARNING: Deprecated flag --model detected; use --model-path instead.
07:12:52.427 INFO: Estimated EP SHMEM buffer memory: 50.87 GiB
07:12:52.427 INFO: Estimated activation memory: 84.87 GiB
07:12:52.427 WARNING: VLM architecture KimiK2_5TextConfig does not implement ArchConfigWithKVAndVisionCache; vision encoder cache memory will not be reserved.
07:12:52.428 WARNING: Architecture 'Eagle3DeepseekV2ForCausalLM' requires max-batch-total-tokens to be specified but found None. Defaulting to the max sequence length of the model: 163840
07:12:52.428 INFO: Automatically enabling overlap scheduling for Eagle3DeepseekV2ForCausalLM with max-num-steps=1. You can manually disable this by setting --no-enable-overlap-scheduler --force.
07:12:52.428 INFO:
07:12:52.428 INFO: ============================================================
07:12:52.428 INFO: Pipeline Configuration (use --pretty-print-config to print full config)
07:12:52.428 INFO: ============================================================
07:12:52.428 INFO:     architecture         : Eagle3DeepseekV2ForCausalLM
07:12:52.428 INFO:     pipeline             : OverlapTextGenerationPipeline
07:12:52.428 INFO:     model                : nvidia/kimi-k2.5-nvfp4
07:12:52.428 INFO:     devices              : gpu[0], gpu[1], gpu[2], gpu[3], gpu[4], gpu[5], gpu[6], gpu[7]
07:12:52.428 INFO:     max_batch_size       : 512
07:12:52.428 INFO:     max_seq_len          : 163840
07:12:52.428 INFO:     cache_memory         : 227.82 GiB
07:12:52.428 INFO:     device_graph_capture : False
07:12:52.428 INFO:
07:12:52.428 INFO: Auto-detected pipeline task: text_generation (model architecture: Eagle3DeepseekV2ForCausalLM)
07:12:52.961 INFO: Starting server...
Starting ASGI metrics server on port 8001
07:12:56.611 INFO: Starting worker: MODEL_5374c57a-7383-4bdd-b021-ea5b0dba64ad
07:12:56.611 INFO: Waiting for model worker readiness
07:13:00.382 INFO: Metrics initialized.
07:13:56.983 INFO: All weight files for nvidia/kimi-k2.5-nvfp4 found in local HF cache.
07:14:00.847 WARNING: Fused MLP is not supported for this model. This may impact performance.
07:14:00.848 INFO: KimiK2_5: data_parallel_degree=8, ep_size=8. Use DP-attention + EP-MoE strategy.
07:14:01.229 INFO: Initializing EP communication infrastructure...
07:14:01.229 INFO: Estimated EP memory usage per device: 6.36 GiB
07:14:05.011 INFO: Initialized EP for node 0
07:14:05.012 INFO: All weight files for nvidia/Kimi-K2.5-Thinking-Eagle3 found in local HF cache.
07:14:05.013 INFO: Eagle3 draft weights are BF16 (no weight_scale_2 found); disabling NVFP4 config for draft.
07:14:18.289 WARNING: Skipping vision model compilation. Vision support is not yet implemented for Kimi Eagle.
07:14:18.289 INFO: Building and compiling eagle3_language_model...
07:14:28.120 INFO: Building eagle3_language_model graph took 9.8 seconds
07:14:51.141 INFO: Compiling eagle3_language_model took 23.0 seconds
07:14:51.141 INFO: Building and compiling eagle3_language_model took 32.9 seconds
07:14:54.726 INFO: Model worker ready
07:14:54.727 INFO:

********************************************************************************

          🚀 Server ready on http://0.0.0.0:8000 (Press CTRL+C to quit)

********************************************************************************

INFO:__main__:Server started in 147.77 seconds
07:14:55.087 INFO: Executed CE batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 32/4096 toks | Context Tokens: 0/163840 toks | Prompt Tput: 231.3 tok/s, Generation Tput: 7.2 tok/s | Batch creation: 11.13ms, Execution: 138.36ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | All Preemptions: 0 reqs
07:14:55.125 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 32/163840 toks | Prompt Tput: 26.8 tok/s, Generation Tput: 26.8 tok/s | Batch creation: 105.21us, Execution: 37.37ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | All Preemptions: 0 reqs
07:14:55.162 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 33/163840 toks | Prompt Tput: 27.5 tok/s, Generation Tput: 27.5 tok/s | Batch creation: 94.74us, Execution: 36.42ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 1/3 (33.33%) accepted, Acceptance Len: 1.00 / 3 toks, Per-Pos: [p0=100%, p1=0%, p2=0%] | All Preemptions: 0 reqs
07:14:55.199 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 35/163840 toks | Prompt Tput: 27.5 tok/s, Generation Tput: 27.5 tok/s | Batch creation: 89.20us, Execution: 36.34ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 3/6 (50.00%) accepted, Acceptance Len: 1.50 / 3 toks, Per-Pos: [p0=100%, p1=50%, p2=0%] | All Preemptions: 0 reqs
07:14:55.236 INFO: Executed TG batch with 1 reqs | Terminated: 1 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 38/163840 toks | Prompt Tput: 26.9 tok/s, Generation Tput: 26.9 tok/s | Batch creation: 123.92us, Execution: 37.18ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 6/9 (66.67%) accepted, Acceptance Len: 2.00 / 3 toks, Per-Pos: [p0=100%, p1=67%, p2=33%] | All Preemptions: 0 reqs
07:14:55.237 INFO: Executed TG batch with 0 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 0/4096 toks | Context Tokens: 0/163840 toks | Prompt Tput: 0.0 tok/s, Generation Tput: 0.0 tok/s | Batch creation: 73.78us, Execution: 208.97us | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 9/12 (75.00%) accepted, Acceptance Len: 2.25 / 3 toks, Per-Pos: [p0=100%, p1=75%, p2=50%] | All Preemptions: 0 reqs
INFO:__main__:Test single request OK. Response: The user wants me to say "hello
INFO:__main__:Running eval with:
 /home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-opt-production/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_python++python+python_3_13_x86_64-unknown-linux-gnu/bin/python3 -m lm_eval --tasks=gsm8k_cot_llama --model=local-chat-completions --log_samples --model_args=model=nvidia/kimi-k2.5-nvfp4,base_url=http://127.0.0.1:8000/v1/chat/completions,num_concurrent=64,max_retries=1,timeout=86400 --apply_chat_template --output_path=/tmp/tmpoywu0p7a --limit=320 --seed=42 --gen_kwargs=seed=42,temperature=0,max_gen_toks=4096 --include_path=/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-opt-production/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/tests/integration/accuracy/smoke_tests/tasks --fewshot_as_multiturn
2026-04-21:07:14:55 WARNING  [config.evaluate_config:281] --limit SHOULD ONLY BE USED FOR TESTING. REAL METRICS SHOULD NOT BE COMPUTED USING LIMIT.
2026-04-21:07:15:00 INFO     [_cli.run:375] Including path: /home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-opt-production/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/tests/integration/accuracy/smoke_tests/tasks
2026-04-21:07:15:00 INFO     [_cli.run:376] Selected Tasks: ['gsm8k_cot_llama']
2026-04-21:07:15:00 INFO     [evaluator:211] Setting random seed to 42 | Setting numpy seed to 42 | Setting torch manual seed to 42 | Setting fewshot manual seed to 42
2026-04-21:07:15:00 WARNING  [evaluator:223] generation_kwargs: {'seed': 42, 'temperature': 0, 'max_gen_toks': 4096} specified through cli, these settings will update set parameters in yaml tasks. Ensure 'do_sample=True' for non-greedy decoding!
2026-04-21:07:15:00 INFO     [evaluator:236] Initializing local-chat-completions model, with arguments: {'model': 'nvidia/kimi-k2.5-nvfp4', 'base_url': 'http://127.0.0.1:8000/v1/chat/completions', 'num_concurrent': 64, 'max_retries': 1, 'timeout': 86400}
2026-04-21:07:15:00 INFO     [models.api_models:172] Using max length 2048 - 1
2026-04-21:07:15:00 INFO     [models.api_models:193] Using tokenizer None
2026-04-21:07:15:00 INFO     [tasks:700] Selected tasks:
2026-04-21:07:15:00 INFO     [tasks:691] Task: gsm8k_cot_llama (/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-opt-production/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/tests/integration/accuracy/smoke_tests/tasks/gsm8k_modular/gsm8k-cot-llama_modular.yaml)
2026-04-21:07:15:00 INFO     [evaluator:314] gsm8k_cot_llama: Using gen_kwargs: {'do_sample': False, 'until': ['<|eot_id|>', '<|start_header_id|>user<|end_header_id|>', 'Q:', '</s>', '<|im_end|>'], 'seed': 42, 'temperature': 0, 'max_gen_toks': 4096}
2026-04-21:07:15:00 WARNING  [evaluator:490] Chat template formatting change affects loglikelihood and multiple-choice tasks. See docs/chat-template-readme.md for details.
2026-04-21:07:15:00 INFO     [api.task:311] Building contexts for gsm8k_cot_llama on rank 0...
100%|█████████████████████████████████████████████| 320/320 [00:03<00:00, 101.49it/s]
2026-04-21:07:15:04 INFO     [evaluator:584] Running generate_until requests
2026-04-21:07:15:04 INFO     [models.api_models:733] Tokenized requests are disabled. Context + generation length is not checked.
Requesting API:   0%|                                        | 0/320 [00:00<?, ?it/s]07:15:04.673 INFO: Executed CE batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1140/4096 toks | Context Tokens: 0/163840 toks | Prompt Tput: 12.7K tok/s, Generation Tput: 11.1 tok/s | Batch creation: 549.28us, Execution: 89.90ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 9/12 (75.00%) accepted, Acceptance Len: 2.25 / 3 toks, Per-Pos: [p0=100%, p1=75%, p2=50%] | All Preemptions: 0 reqs
07:15:05.138 INFO: Executed CE batch with 32 reqs | Terminated: 0 reqs, Pending: 11 reqs | Input Tokens: 29203/4096 toks | Context Tokens: 4096/163840 toks | Prompt Tput: 63.3K tok/s, Generation Tput: 69.3 tok/s | Batch creation: 2.73ms, Execution: 461.70ms | KVCache usage: 0.2% of 53512 blocks, Cache hit rate: 12.3% | Draft Tokens: 9/12 (75.00%) accepted, Acceptance Len: 2.25 / 3 toks, Per-Pos: [p0=100%, p1=75%, p2=50%] | All Preemptions: 0 reqs
07:15:05.239 INFO: Executed CE batch with 38 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 4725/4096 toks | Context Tokens: 38912/163840 toks | Prompt Tput: 48.1K tok/s, Generation Tput: 387.1 tok/s | Batch creation: 2.50ms, Execution: 98.16ms | KVCache usage: 0.3% of 53512 blocks, Cache hit rate: 88.0% | Draft Tokens: 9/12 (75.00%) accepted, Acceptance Len: 2.25 / 3 toks, Per-Pos: [p0=100%, p1=75%, p2=50%] | All Preemptions: 0 reqs
07:15:05.285 INFO: Executed TG batch with 64 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 64/4096 toks | Context Tokens: 73464/163840 toks | Prompt Tput: 1.4K tok/s, Generation Tput: 1.4K tok/s | Batch creation: 489.03us, Execution: 44.88ms | KVCache usage: 0.3% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 9/12 (75.00%) accepted, Acceptance Len: 2.25 / 3 toks, Per-Pos: [p0=100%, p1=75%, p2=50%] | All Preemptions: 0 reqs
07:15:05.329 INFO: Executed TG batch with 64 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 64/4096 toks | Context Tokens: 73528/163840 toks | Prompt Tput: 1.5K tok/s, Generation Tput: 1.5K tok/s | Batch creation: 528.71us, Execution: 43.65ms | KVCache usage: 0.3% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 165/204 (80.88%) accepted, Acceptance Len: 2.43 / 3 toks, Per-Pos: [p0=88%, p1=85%, p2=69%] | All Preemptions: 0 reqs
...
07:16:32.836 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4586/163840 toks | Prompt Tput: 27.3 tok/s, Generation Tput: 27.3 tok/s | Batch creation: 104.62us, Execution: 36.69ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112053/164109 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:32.874 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4590/163840 toks | Prompt Tput: 26.8 tok/s, Generation Tput: 26.8 tok/s | Batch creation: 91.74us, Execution: 37.29ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112056/164112 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:32.911 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4594/163840 toks | Prompt Tput: 27.6 tok/s, Generation Tput: 27.6 tok/s | Batch creation: 88.38us, Execution: 36.28ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112059/164115 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:32.949 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4598/163840 toks | Prompt Tput: 26.6 tok/s, Generation Tput: 26.6 tok/s | Batch creation: 111.60us, Execution: 37.60ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112059/164118 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:32.986 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4599/163840 toks | Prompt Tput: 26.8 tok/s, Generation Tput: 26.8 tok/s | Batch creation: 117.49us, Execution: 37.36ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112062/164121 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:33.025 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4603/163840 toks | Prompt Tput: 26.4 tok/s, Generation Tput: 26.4 tok/s | Batch creation: 90.20us, Execution: 37.85ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112065/164124 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:33.063 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4607/163840 toks | Prompt Tput: 26.2 tok/s, Generation Tput: 26.2 tok/s | Batch creation: 116.97us, Execution: 38.18ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112068/164127 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:33.101 INFO: Executed TG batch with 1 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4611/163840 toks | Prompt Tput: 26.7 tok/s, Generation Tput: 26.7 tok/s | Batch creation: 121.24us, Execution: 37.49ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112071/164130 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:33.138 INFO: Executed TG batch with 1 reqs | Terminated: 1 reqs, Pending: 0 reqs | Input Tokens: 1/4096 toks | Context Tokens: 4615/163840 toks | Prompt Tput: 27.4 tok/s, Generation Tput: 27.4 tok/s | Batch creation: 105.69us, Execution: 36.50ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112074/164133 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
07:16:33.139 INFO: Executed TG batch with 0 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 0/4096 toks | Context Tokens: 0/163840 toks | Prompt Tput: 0.0 tok/s, Generation Tput: 0.0 tok/s | Batch creation: 85.65us, Execution: 183.80us | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 112074/164136 (68.28%) accepted, Acceptance Len: 2.05 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
Requesting API: 100%|██████████████████████████████| 320/320 [01:29<00:00,  3.59it/s]
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2026-04-21:07:16:34 INFO     [loggers.evaluation_tracker:247] Saving results aggregated
2026-04-21:07:16:34 INFO     [loggers.evaluation_tracker:119] Saving per-task samples to /tmp/tmpoywu0p7a/nvidia__kimi-k2.5-nvfp4/*.jsonl
local-chat-completions ({'model': 'nvidia/kimi-k2.5-nvfp4', 'base_url': 'http://127.0.0.1:8000/v1/chat/completions', 'num_concurrent': 64, 'max_retries': 1, 'timeout': 86400}), gen_kwargs: ({'seed': 42, 'temperature': 0, 'max_gen_toks': 4096}), limit: 320.0, num_fewshot: None, batch_size: 1
|     Tasks     |Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|---------------|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k_cot_llama|      4|flexible-extract|     8|exact_match|↑  |0.9719|±  |0.0093|
|               |       |strict-match    |     8|exact_match|↑  |0.9563|±  |0.0115|

07:16:35.484 INFO: Shutting down workers...

Aborted!
WARNING:inference_server_harness:Server did not stop after ctrl-c, trying SIGTERM
INFO:__main__:[ EvalSummary(gpu_name='NVIDIA B200',
              gpu_count=8,
              startup_time_seconds=147.77,
              eval_task='gsm8k_cot_llama',
              task_type='text',
              accuracy=0.971875,
              accuracy_stderr=0.009256698730918323,
              total_evaluation_time_seconds=96.79239700688049,
              task_hash='7decde76193f5360fe90480a5000abf9f3d672d7dbac9f333e80f86b804c0add')]
```
MODULAR_ORIG_COMMIT_REV_ID: 1a656755de514993f01a04859a8e77eeb06e1316