[KV] Disable Jenga padding
Currently Jenga padding is not needed for any models so disable by
default
as it breaks stuff like SSM models + KV offload.
```
ValueError: KVCacheMemory buffer must be contiguous, but this one has
shape (448, 16777216) with strides (19169280, 1): its pages are padded,
```

We can enable it via env var. We will need to re-enable it once we get
around to dsv4 support.

MODULAR_ORIG_COMMIT_REV_ID: 69d91110abee008d8f0e8f7dd93cc592b640643e