[MAX] Disable auto enable overlap scheduler and graph capture for non text gen archs
Fixes mpnet failure. Embedding model does not work with these features.
```
[Internal link]

     ^
  File "/home/runner/.cache/bazel/_bazel_runner/e5185c6d580a8eeb67820192d4a9baf7/execroot/_main/bazel-out/k8-opt-ci-build/bin/max/tests/integration/accuracy/verify_pipelines.runfiles/_main/max/tests/integration/test_common/process_isolation.py", line 133, in run_in_isolated_process
    raise exception
ValueError: Overlap scheduler requires the TEXT_GENERATION pipeline task, got task=PipelineTask.EMBEDDINGS_GENERATION.

===== Finished sentence-transformers/all-mpnet-base-v2-float32 (11s) =====

----------------------------------------

Ran on node: mia1-p02-g40

| Status | Model |
| :---:  | :---  |
| ❌ | all-mpnet-base-v2-float32 | N/A |
```

Fixes QUA-460

MODULAR_ORIG_COMMIT_REV_ID: 409f14733090b6afea672943aecb17be55f0a04a