[mojo-lang] Explicitly disallow VariadicList(Mem) on traits for now (#28422)
Motivated by [Internal link]

Currently we cannot express a VariadicList containing types that conform
to a trait, e.g.
```
fn takeOne[T: Stringable](x: T):
    print(str(x))

fn takeMany[T: Stringable](*xs: T):
    for i in xs:
        print(str(i))

fn main():
    # Bool conforms to Stringable
    let a: Bool = True
    takeOne(a)     # OK
    takeMany(a)    # ERROR
```

Doing it today gets you this ("aka" mine):
```
error: cannot implicitly convert
    'variadic<!lit.ref<mut :trait<_"$builtin"::_"$str"::_Stringable> T, *"`xs">>'
value to
    'VariadicListMem[T, *"`xs"]'
        (aka 'variadic<!lit.ref<mut :AnyRegType T, *"`xs">>')
in def argument shadow
```

This is clearer when considering how you'd write the expected type
```variadic<!lit.ref<mut :trait<_"$builtin"::_"$str"::_Stringable> T,
*"`xs">>``` in Mojo.

In order to make a `VariadicList` (or `VariadicListMem`) remember that
`T` is Stringable, you'd need `VariadicList` to take an additional
parameter `T: Stringable`, and then pass `T` as the elem type. But
`VariadicList` does not have this additional parameter today, and I'm
not sure this is a good idea:

```
# I just made up AnyTraitType.
struct VariadicList[trait: AnyTraitType, type: trait]:
```

since that would mean any struct that accepts type params may one day
need additional trait params if any user wants to use the struct without
"erasing" any trait knowledge.

Coincidentally, this should benefit from our existing discussion on the
colon syntax, specifically around relating types, traits, and metatypes
([updated
[Internal link]
for next discussion). For now, we can preemptively disallow this with a
better error message:

```
error: unsupported variadic on trait-conforming types
```

MODULAR_ORIG_COMMIT_REV_ID: 4f8fbdf47502cabb70e293bde81e038b824a4e60