[External] [stdlib] Make `UInt` `Hashable` again (#47433)
[External] [stdlib] Make `UInt` `Hashable` again

### Problem
Calling `hash` on a `UInt` value doesn't compile, e.g.

```mojo
def main():
    var x: UInt = 1234
    hash(x)
```

results in

```
error: no matching function in call to 'hash'
    hash(u)
    ~~~~^~~
```

even though it does compile for `UInt8`, `UInt16`, `UInt32`, and
`UInt64`. This means using `UInt` as a key to `Dict` doesn't compile
either, for example

```mojo
from collections import Dict

def main():
    var d = Dict[UInt, String]()
```

results in

```
error: 'Dict' parameter #0 has 'KeyElement' type, but value has type 'AnyStruct[UInt]'
    var d = Dict[UInt, String]()
                 ^~~~
```

### Fix
This _does_ work for `Int8` through `Int64` as well as `Int` itself, so
I essentially copied over the definition of `Int.__hash__` with the
appropriate change to the underlying `DType` passed to `_hash_simd`,
under the assumption it should work the same for `UInt`. Added a (very
simple) test similar to that for `String.__hash__` too.

Co-authored-by: Derek Smith <derekcs@pm.me>
Closes modularml/mojo#3491
MODULAR_ORIG_COMMIT_REV_ID: c258aaeba7adf7927a5d401e2c2432ef914b8abf