[Lit] Fix incorrect diagnostic when substituting parameter types. (#6562)
This fixes an issue where a parameter type mismatch would complain
about the unsubstituted type in the diagnostic instead of using the
one it is actually looking for, this can be incredibly confusing!

Before:
```
error: invalid call to 'badReboundType': callee parameter "val" has '__mlir_type.!pop.scalar<type>' type, but value has type '__mlir_type.!pop.scalar<f32>'
```

After:
```
error: invalid call to 'badReboundType': callee parameter "val" has '__mlir_type.!pop.scalar<f64>' type, but value has type '__mlir_type.!pop.scalar<f32>'
```

MODULAR_ORIG_COMMIT_REV_ID: e689bc2b2827e15a9b1478ee825e3f34723abae8