[bazel] Move from strip_include_prefix to includes (#55004)
strip_include_prefix triggers bazel to create a separate directory
called _virtual_includes and symlink the necessary headers there for
each library that uses it.

includes instead propagates the direct path to the headers (which is
also a symlink tree of only things defined in the dep tree).

The result of this is that instead of having separate include paths for
every transitive library, libraries that share the same root include
directory are deduped.

For example for support, before:

```
-iquote bazel-out/k8-fastbuild/bin/Support/_virtual_includes/CPUCache
-iquote bazel-out/k8-fastbuild/bin/Support/_virtual_includes/DeviceSpecs
```

After:

```
-iquote Support/include
```

This has massive impact on the overall number of include paths, for mojo
this reduces the include paths by 60. The algorithm for finding headers
via include paths is N^2d so this should also have a positive impact on
build time (since it also applies to every compile action).

The other upside to this is previous errors could have the
virtual_include paths in them, which while it was a symlink to the same
source file, it was confusing and annoying.

Before:

```
Support/lib/Profiling/TimeProfiler.cpp:71:3: error: no viable constructor or deduction guide for deduction of template arguments of 'TimeTraceScope'
   71 |   TimeTraceScope("");
      |   ^
bazel-out/k8-fastbuild/bin/Support/_virtual_includes/Profiling/Support/Profiling/TimeProfiler.h:1170:8: note: candidate template ignored: could not match 'TimeTraceScope<Type, Enabled, DumpFnT>' against 'const char *'
 1170 | struct TimeTraceScope {
      |        ^
```

After:

```
Support/lib/Profiling/TimeProfiler.cpp:71:3: error: no viable constructor or deduction guide for deduction of template arguments of 'TimeTraceScope'
   71 |   TimeTraceScope("");
      |   ^
Support/include/Support/Profiling/TimeProfiler.h:1170:8: note: candidate template ignored: could not match 'TimeTraceScope<Type, Enabled, DumpFnT>' against 'const char *'
 1170 | struct TimeTraceScope {
      |        ^
```

Note that the first path was always correct, but the header paths it
included were annoying.

I believe this change is 100% upside.

MODULAR_ORIG_COMMIT_REV_ID: 70d10ee74a0c366ef7d808e28a36b0e18945cc51