Not sure if it will fix the import issue but worth a try.
Original error:
```
ImportError: cannot import name 'MHAMaskVariant' from 'max.nn.kernels
```

Now instead of importing from parent dir, we import from a file in same
subdir.
The new mask_config.py file does not have very many things in it. It
does not import other files as well.
```
// before
from ..kernels import MHAMaskVariant

// after
from .mask_config import MHAMaskVariant
```

I also fix the glob pattern in BUILD file for distributed gpu tests.

Thanks for catching my mistake @AustinDoolittle :)

MAX_INTEGRATION_TESTS_REV_ID: 5105621661186c3f6129113b0445a0e667b00dd7