[MAX] Fix idefics3 initialize signature error due to mid air collision
Two commit landed in parallel. This caused:
```
max/python/max/pipelines/architectures/idefics3_modulev3/model_config.py:122: error:
Signature of "initialize" incompatible with supertype
"max.pipelines.lib.interfaces.arch_config.ArchConfig"  [override]
        def initialize(cls, pipeline_config: PipelineConfig) -> Self:
        ^
max/python/max/pipelines/architectures/idefics3_modulev3/model_config.py:122: note:      Superclass:
max/python/max/pipelines/architectures/idefics3_modulev3/model_config.py:122: note:          @classmethod
max/python/max/pipelines/architectures/idefics3_modulev3/model_config.py:122: note:          def initialize(cls, pipeline_config: PipelineConfig, model_config: MAXModelConfig | None = ...) -> Idefics3Config
max/python/max/pipelines/architectures/idefics3_modulev3/model_config.py:122: note:      Subclass:
max/python/max/pipelines/architectures/idefics3_modulev3/model_config.py:122: note:          @classmethod
max/python/max/pipelines/architectures/idefics3_modulev3/model_config.py:122: note:          def initialize(cls, pipeline_config: PipelineConfig) -> Idefics3Config
Found 1 error in 1 file (checked 404 source files)
```

This pr fixes it

MODULAR_ORIG_COMMIT_REV_ID: 91575a62305964c66e800261c5bc9e5132a09c85