Revert "[mojo-lang] Replace ParameterEvaluator with ParserParamEvaluator" (#38848)
Reverts [Internal link]

Broke main with:

```
/__w/modular/modular/KGEN/lib/MojoParser/ParserParamEvaluator.cpp:76:40: error: type 'M::InterpreterState' is not a direct or virtual base of 'M::KGEN::LIT::ParserParamEvaluator'
    : ParameterEvaluator(paramValues), InterpreterState(resolver.getContext()),
                                       ^~~~~~~~~~~~~~~~
```

MODULAR_ORIG_COMMIT_REV_ID: f38a82d02cb1db4330c7cc4426f8d54701711a16