Revert "[Graph API] Make Dim an alias for int | str " (#44875)
Broke main:

```
SDK/test/API/graph/python/pytests/conftest.py:18: in <module>
    from max.graph import DType, TensorType
SDK/lib/GraphAPI/python/max/graph/__init__.py:12: in <module>
    from .type import TensorType, Type, DimLike
E   ImportError: cannot import name 'DimLike' from 'max.graph.type' (/work/remotebuilds/924eebe9-1135-4431-929a-ec49bb75ac2b/bazel-out/aarch64-opt-release/bin/SDK/test/API/graph/python/tests.runfiles/_main/SDK/lib/GraphAPI/python/max/graph/type.py)
```

Reverts [Internal link]

MAX_GRAPH_API_ORIG_REV_ID: 9db7deb45196bae0d70ccd98d22a3deae2de60e0