[MAX] Fix python distributed broadcast import for non-GPU toolchains
For non-gpu toolchains, this would crash with an import error:
```
    File "/buildbuddy/remotebuilds/8ce656f3-13a7-4b00-a1d0-497e770c31aa/bazel-out/k8-opt-ci-build/bin/oss/modular/bazel/internal/sphinx.runfiles/_main/max/python/max/_distributed_ops/__init__.py", line 23, in <module>
      from .distributed_ops import (  # type: ignore[import-not-found]
          broadcast_kernel as _broadcast_kernel,
      )
    File "/buildbuddy/remotebuilds/8ce656f3-13a7-4b00-a1d0-497e770c31aa/bazel-out/k8-opt-ci-build/bin/oss/modular/bazel/internal/sphinx.runfiles/_main/oss/modular/mojo/python/mojo/importer.py", line 168, in find_spec
      _compile_mojo_to_so(root_mojo_path, expected_cache_file)
      ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/buildbuddy/remotebuilds/8ce656f3-13a7-4b00-a1d0-497e770c31aa/bazel-out/k8-opt-ci-build/bin/oss/modular/bazel/internal/sphinx.runfiles/_main/oss/modular/mojo/python/mojo/importer.py", line 87, in _compile_mojo_to_so
      raise ImportError(
          "Import of Mojo module failed due to compilation error."
      ) from error
  ImportError: Import of Mojo module failed due to compilation error.
```

MODULAR_ORIG_COMMIT_REV_ID: bf552f53c91cd902dd87fb6ef2d928147d6aefec