Revert "[mojo-lang][KGEN] Move more signature verification into SignatureType" (#20207)
Reverts [Internal link] This breaks the [MojoHub
[Internal link]
with error:

```
Error executing cell 5:
error: Expression [2]:97:34: unexpected character
            _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                                 ^

error: Expression [2]:97:32: invalid MLIR type: !kgen.pointer<scalar<f32>>>
            _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                    ~~~~~~~~~~~^~~

Expression [2]:97:32: MLIR error: found trailing characters: '>'
            _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                               ^

error: Expression [2]:106:34: unexpected character
            _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                                 ^

error: Expression [2]:106:32: invalid MLIR type: !kgen.pointer<scalar<f32>>>
            _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                    ~~~~~~~~~~~^~~

Expression [2]:106:32: MLIR error: found trailing characters: '>'
            _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                               ^

error: Expression [2]:62:38: unexpected character
                _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                                     ^

error: Expression [2]:62:36: invalid MLIR type: !kgen.pointer<scalar<f32>>>
                _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                        ~~~~~~~~~~~^~~

Expression [2]:62:36: MLIR error: found trailing characters: '>'
                _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                                   ^

error: Expression [2]:71:38: unexpected character
                _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                                     ^

error: Expression [2]:71:36: invalid MLIR type: !kgen.pointer<scalar<f32>>>
                _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
                        ~~~~~~~~~~~^~~

Expression [2]:71:36: MLIR error: found trailing characters: '>'
                _type : __mlir_type.`!kgen.pointer<scalar<f32>>>`
```

MODULAR_ORIG_COMMIT_REV_ID: cdc0dac68f8e1e0c7dda8dabdd5902af7fd44fb0