[ZMQ] Do not use shm encoding for ZMQ router dealer sockets as they can be used for internode communication
When running internode DI, I got the error below.

This error occured since we serialized the text context array via shm
and
shuttled the encoded data from decode -> prefill. As the prefill was on
a
different node, the shm file did not exist. As such it threw an file not
found error.

This PR fixes this issue by disabling shm encoding for router dealer
sockets.
Currently our push / pull sockets are mostly used for intra-node
communication
and the router / dealer sockets are only used for inter-node
communication.
As such router / dealer defaults to this being disabled while push
sockets
default to this being enabled but can be overridden.

```
x08\xc5\x05 \x00\x00\x06 \x00\x08\xc5\x05 \x00\x00\x06 \x00\x08\xc5\x05 \x00\x00\x06 \x00\x08\xc5\x05 \x00\x00\x06 \x00\x08\xc5\x05 \x00\x00\x06 \x00\x08\xc5\x05 \x00\x00\x06 \x00\x08\xc5\x05 \x00\x00\x06 \x00|')
[AsyncRT/lib/NIXL/nixl_agent.cpp:1246] Loading remote metadata for agent: decode_agent_1fd86c36-bc47-41b0-90f2-af809879574f_0_1
end load_remote_metadata with b'decode_agent_1fd86c36-bc47-41b0-90f2-af809879574f_0_1'
end decode with decode_agent_1fd86c36-bc47-41b0-90f2-af809879574f_0_1
done connecting to remote transfer engine
Sending transfer engine metadata to b'\x00kx\xdc>'
done sending transfer engine metadata to dispatcher
Process MODEL_bd6cb4d2-7b8e-4b69-b6ee-41e4d4b4dcf9:
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/examples/di/di.runfiles/_main/max/python/max/interfaces/utils/shared_memory.py", line 134, in open_shm_array
    shm = shared_memory.SharedMemory(name=meta["name"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/examples/di/di.runfiles/rules_python++python+python_3_12_x86_64-unknown-linux-gnu/lib/python3.12/multiprocessing/shared_memory.py", line 104, in __init__
    self._fd = _posixshmem.shm_open(
               ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/maximg-f7be2d54d8fe4c9c97b48d3054fbbfa9'
...
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/examples/di/di.runfiles/_main/max/python/max/serve/scheduler/prefill_scheduler.py", line 264, in run_iteration
    request, identity = self.dispatcher.recv_request_nowait()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/examples/di/di.runfiles/_main/max/python/max/serve/queue/zmq_queue.py", line 286, in recv_request_nowait
    msg = self._deserialize(serialized_msg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/examples/di/di.runfiles/_main/max/python/max/interfaces/utils/serialization.py", line 197, in __call__
    return self._decoder.decode(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/examples/di/di.runfiles/_main/max/python/max/interfaces/utils/serialization.py", line 250, in decode_numpy_array
    return open_shm_array(obj)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/examples/di/di.runfiles/_main/max/python/max/interfaces/utils/shared_memory.py", line 136, in open_shm_array
    raise RuntimeError(
RuntimeError: Failed to open shared memory array in consumer: [Errno 2] No such file or directory: '/maximg-f7be2d54d8fe4c9c97b48d3054fbbfa9'
python3: pthread_mutex_lock.c:94: ___pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
```
MODULAR_ORIG_COMMIT_REV_ID: ba326a57458d242763dd2f242e3c2689f41627c0