[mojo-lldb] Fix windows build. (#17530)
The build was failing with:

```
C:\actions-runner\_work\modular\modular\KGEN\tools\mojo\REPL\mojo-repl.cpp(37): error C2440: '<function-style-cast>': cannot convert from 'const std::filesystem::path::value_type *' to 'llvm::ArrayRef<llvm::StringRef>'
C:\actions-runner\_work\modular\modular\KGEN\tools\mojo\REPL\mojo-repl.cpp(37): note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

disambiguate to unbreak the build.

MODULAR_ORIG_COMMIT_REV_ID: 054bf37e62ceed68fadc411b02a02fd28cfe33a2