[Support][CMake] Fix MTelemetry dependencies on Windows. (#28087)
This patch fixes the issue we started to see once Telemetry started to depend on Entitlements on Windows:
```
C:\actions-runner\_work\modular\modular\Support\include\Support/Cryptography/Keypair.h(12): fatal error C1083: Cannot open include file: 'mbedtls/pk.h': No such file or directory
```

This essentially means that CMake isn't properly tracking the include directory dependency, so this patch should fix that.

MODULAR_ORIG_COMMIT_REV_ID: 8947c0fb2afceb8e301ab9b4778f5ecd957961a9