[SDK] Eager failures for mismatched devices in ops
The compiler already knows the expected semantics for what devices ops
expect their operands to be on, but this lives at the wrong layer. We
expose these failures during RMO -> MO lowering. This PR teaches RMO
about these same semanics so we can fail eagerly at op construction
time.

It additionally adds defensive checks to graph ops. I centralized this
in `ops.validation.assert_same_devices(...)` so we get a consistent
error message across ops. The follow ops now defensively check for same
device inputs and have tests for this behavior:

- all binary elementwise ops
- buffer_store_slice
- concat
- conv2d / conv2d_transpose
- gather / gather_nd
- scatter / scatter_nd
- matmul
- outer
- stack
- where

Example:

```
from max.experimental import random
from max.driver import Accelerator, CPU

random.uniform([1], device=Accelerator()) + random.uniform([1], device=CPU())
```

previously failed with
```
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 742, in evaluate
    model = _session().load(self.graph)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/engine/api.py", line 408, in load
    _model = self._impl.compile_from_object(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Failed to run the MOToMGP pass manager:

Build Time Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/random.py", line 98, in uniform
    return uniform_like(type, range=range)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/functional.py", line 58, in wrapped
    results = op(*args, **kwargs)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/graph/ops/random.py", line 121, in uniform
    return Graph.current._add_op_generated(

MAX Compile Error: input device cpu:0 must match result device gpu:0 in rebind

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 492, in __repr__
    return f"{self.type}: [{', '.join(str(v) for v in self._values())}]"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 492, in <genexpr>
    return f"{self.type}: [{', '.join(str(v) for v in self._values())}]"
                                                      ^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 465, in _values
    self._sync_realize()
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 436, in _sync_realize
    return asyncio.run(self.realize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/external/rules_python++python+python_3_12_x86_64-unknown-linux-gnu/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/external/rules_python++python+python_3_12_x86_64-unknown-linux-gnu/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/external/rules_python++python+python_3_12_x86_64-unknown-linux-gnu/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 423, in realize
    return await self
           ^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 416, in __await__
    yield from asyncio.create_task(GRAPH.evaluate(self))
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 751, in evaluate
    raise RuntimeError(
RuntimeError: Failed to compile and execute graph! Please file an issue. This error should have been caught at op creation time.
```

now fails with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/tensor.py", line 764, in __add__
    return F.add(self, rhs)
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/experimental/functional.py", line 66, in wrapped
    results = op(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/graph/ops/elementwise.py", line 60, in elementwise_op
    assert_same_device(lhs=lhs, rhs=rhs)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/SDK/python.runfiles/_main/SDK/lib/API/python/max/graph/ops/validation.py", line 36, in assert_same_device
    raise ValueError(
ValueError: Input values must be on the same device
    lhs: TensorType(dtype=bfloat16, shape=[Dim(1)], device=gpu:0)
    rhs: TensorType(dtype=float32, shape=[Dim(1)], device=cpu:0)
```
MODULAR_ORIG_COMMIT_REV_ID: c89b7034a2f7c5ee2385b288e891d552272773f4