[mojo-lang] Untyped default args convert to `object` (#13625)
The following Mojo program emits a poor error message:

```
def foo(x, y, z = "123"): pass
```

```
error: argument #3 has type '!pop.pointer<@"$Object"::@object>' but default argument has type '!kgen.declref<@"$StringLiteral"::@StringLiteral>'
def f(x, y, z = "123"):
^
```

This occurs because the type expression for `z` is null, and so no type
conversion occurs between the default argument expression `"123"` (of
type `StringLiteral`) and the `z` argument type, which in a `def`
context is `object` type.

Detect this case and convert default arguments in this context to
`object` type.

Currently, conversion to `object` type always fails: `object` type is
not register passable, and so a compile-time value cannot be constructed
for the default argument value. Still, the error message is nicer:

```
error: cannot synthesize lvalue in default argument
def f(x, y, z = "123"):
                ^
```

This patch also adds tests; not only for the `def` case, but also for
error cases in which default argument values are emitted for
non-register-passable types (previously untested).

Closes #13548.
MODULAR_ORIG_COMMIT_REV_ID: ac70231daa54264b72b7d5e83a46333068690893