[examples] Add pixi manifest and fix runtime_checkable error
This enables testing for nightly builds via `pixi run test`. In doing
so, discovered a bug because the `nn.Linear` type is not a concrete
class so the code resulted in:

```
TypeError: Instance and class checks can only be used with @runtime_checkable protocols
```

Instead reading the class name does the job. (Or we’d have to add
`@runtime_checkable` to the Linear class.)

MODULAR_ORIG_COMMIT_REV_ID: 1604a2739d54f87344b7b9cbaa33924663dfe1d9