[Eagle] Support device graphs with num_speculative_tokens > 1
Previously the cuda graph key was (batch_size, num_partitions,
q_max_seq_len).
Now the key is (batch_size, num_partition, q_max_seq_len,
draft_num_partition).

We basically added draft_num_partition to the key.

We use `num_partition` for `target` and `draft0`. We use
`draft_num_partition` for `draft1` ... `draftK`.

<img width="1146" height="242" alt="image"
src="https://github.com/user-attachments/assets/a53af29d-c772-495a-ba92-b706edc038f6"
/>

target metadata: `[batch_size, 5,
num_partitions=compute_mla_dispatch_args_scalar(batch_size,
max_cache_valid_length, 5, ...)]`
draft1-k metadata: `[batch_size, 1,
num_partitions=compute_mla_dispatch_args_scalar(batch_size,
max_cache_valid_length, 1, ...)]`

Graph capture warmup works like:
```
// batch_size=42
max_cache_length = 0 -> num_partition=1, draft_num_partition=1 (graph1)
max_cache_length = 1 -> num_partition=3, draft_num_partition=5 (graph2)
max_cache_length = 128 -> num_partition=3, draft_num_partition=7 (graph3)
max_cache_length = 256 -> num_partition=3, draft_num_partition=7 (graph4)
...
max_cache_length = 8192 -> num_partition=4, draft_num_partition=8 (graph99)

// final set of graphs for batch_size=42
{(42, 5, 1, 1) -> graph1, (42, 5, 3, 5) -> graph2, (42, 5, 3, 7) -> graph4, ..., (42, 5, 4, 8) -> graph99}
```

```
% br smoke-test -- nvidia/Kimi-K2.5-NVFP4__eagle --disable-timeouts
...
21:14:59.823 INFO: Pre-capturing overlap device graphs for decode batch sizes [1..128] with num_steps=1.
Capturing device graph shapes: 100%|█| 128/128 [04:13<00:00,  1.98s/
21:19:13.145 INFO: Overlap device graph pre-capture complete for decode batch sizes [1..128] with num_steps=1.
...
21:35:49.192 INFO: Executed TG batch with 8 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 8/4096 toks | Context Tokens: 4993/163840 toks | Prompt Tput: 617.4 tok/s, Generation Tput: 617.4 tok/s | Batch creation: 311.56us, Execution: 12.96ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 115705/170028 (68.05%) accepted, Acceptance Len: 2.04 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
use_graph_capture_replay=True runner=<max.pipelines.lib.graph_capture.ServeGraphCaptureRunner object at 0x7712ec45d940> inputs.batch_type=<BatchType.TG: 'TG'> num_draft_tokens_to_verify=3
replay_graph_key=(8, 37, 4, 64)
21:35:49.205 INFO: Executed TG batch with 8 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 8/4096 toks | Context Tokens: 4997/163840 toks | Prompt Tput: 616.6 tok/s, Generation Tput: 616.6 tok/s | Batch creation: 281.98us, Execution: 12.97ms | KVCache usage: 0.1% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 115708/170031 (68.05%) accepted, Acceptance Len: 2.04 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
use_graph_capture_replay=True runner=<max.pipelines.lib.graph_capture.ServeGraphCaptureRunner object at 0x7712ec45d940> inputs.batch_type=<BatchType.TG: 'TG'> num_draft_tokens_to_verify=3
replay_graph_key=(8, 37, 4, 64)
21:35:49.218 INFO: Executed TG batch with 8 reqs | Terminated: 1 reqs, Pending: 0 reqs | Input Tokens: 8/4096 toks | Context Tokens: 5001/163840 toks | Prompt Tput: 626.3 tok/s, Generation Tput: 626.3 tok/s | Batch creation: 308.18us, Execution: 12.77ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 115709/170034 (68.05%) accepted, Acceptance Len: 2.04 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
Requesting API: 100%|█████████████████████████████████████████████████████████████| 320/320 [00:48<00:00,  6.63it/s]
21:35:49.232 INFO: Executed TG batch with 0 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 0/4096 toks | Context Tokens: 0/163840 toks | Prompt Tput: 0.0 tok/s, Generation Tput: 0.0 tok/s | Batch creation: 66.36us, Execution: 12.95ms | KVCache usage: 0.0% of 53512 blocks, Cache hit rate: 0.0% | Draft Tokens: 115709/170037 (68.05%) accepted, Acceptance Len: 2.04 / 3 toks, Per-Pos: [p0=85%, p1=68%, p2=52%] | All Preemptions: 0 reqs
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2026-04-21:21:35:50 INFO     [loggers.evaluation_tracker:247] Saving results aggregated
2026-04-21:21:35:50 INFO     [loggers.evaluation_tracker:119] Saving per-task samples to /tmp/tmpyajqp300/nvidia__kimi-k2.5-nvfp4/*.jsonl
local-chat-completions ({'model': 'nvidia/kimi-k2.5-nvfp4', 'base_url': 'http://127.0.0.1:8000/v1/chat/completions', 'num_concurrent': 64, 'max_retries': 1, 'timeout': 86400}), gen_kwargs: ({'seed': 42, 'temperature': 0, 'max_gen_toks': 4096}), limit: 320.0, num_fewshot: None, batch_size: 1
|     Tasks     |Version|     Filter     |n-shot|  Metric   |   |Value |   |Stderr|
|---------------|------:|----------------|-----:|-----------|---|-----:|---|-----:|
|gsm8k_cot_llama|      4|flexible-extract|     8|exact_match|↑  |0.9719|±  |0.0093|
|               |       |strict-match    |     8|exact_match|↑  |0.9594|±  |0.0111|

21:35:51.439 INFO: Shutting down workers...
WARNING:inference_server_harness:Server did not stop after ctrl-c, trying SIGTERM
WARNING:inference_server_harness:Process did not terminate gracefully, forcing kill
INFO:__main__:[ EvalSummary(gpu_name='NVIDIA B200',
              gpu_count=8,
              startup_time_seconds=391.8,
              eval_task='gsm8k_cot_llama',
              task_type='text',
              accuracy=0.971875,
              accuracy_stderr=0.009256698730918323,
              total_evaluation_time_seconds=55.573263126192614,
              task_hash='7decde76193f5360fe90480a5000abf9f3d672d7dbac9f333e80f86b804c0add')]
```

I came across errors like this while implementing this PR:
```
RuntimeError: No captured device graph for (8, 37, 4, 32). Available num_partitions for batch_token_count=8: [32]. Available batch_token_counts: [8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488, 496, 504, 512, 520, 528, 536, 544, 552, 560, 568, 576, 584, 592, 600, 608, 616, 624, 632, 640, 648, 656, 664, 672, 680, 688, 696, 704, 712, 720, 728, 736, 744, 752, 760, 768, 776, 784, 792, 800, 808, 816, 824, 832, 840, 848, 856, 864, 872, 880, 888, 896, 904, 912, 920, 928, 936, 944, 952, 960, 968, 976, 984, 992, 1000, 1008, 1016, 1024].
```

This occurs when we do not capture a viable (num_partition,
draft_num_partition) pair
during warmup. This is because our cache length probe strategy missed
some
cases. I improved the probe strategy to hopefully catch all viable pairs
via adding some more entries to the probe list.

```
    # OLD
    probe_lengths = (
        [1]
        + list(range(self.granularity, max_cache_length, self.granularity))
        + [max_cache_length]
    )

    # NEW
    if q_max_seq_len > 1:
        # With spec decoding, we need to probe a few more entries to hit all
        # viable (num_partition, draft_num_partition) pairs. This was determined
        # experimentally and is highly fragile. The alternative is to brute
        # force capture all 11 x 11 = 121 pairs but that would increase graph
        # capture time significantly. In practice, I only noticed that we used
        # ~20 of the 121 combos for Kimi.
        additional_probes = list(
            range(self.granularity - 1, max_cache_length, self.granularity)
        )
        probe_lengths.extend(additional_probes)
```

You can take a look at probe.py and parse.py here to see how I came up
with
this new probe strategy:
[Internal link]

For example, see:
```
--------------------------------
batch_size=1
--------------------------------
len(brute_force)=22
brute_force={(1, 1, 4, 1): (low=1, high=124), (1, 2, 4, 1): (low=125, high=127), (1, 2, 4, 2): (low=128, high=252), (1, 4, 4, 2): (low=253, high=255), (1, 4, 4, 4): (low=256, high=508), (1, 8, 4, 4): (low=509, high=511), (1, 8, 4, 8): (low=512, high=1020), (1, 9, 4, 8): (low=1021, high=1023), (1, 9, 4, 9): (low=1024, high=1148), (1, 16, 4, 9): (low=1149, high=1151), (1, 16, 4, 16): (low=1152, high=2044), (1, 18, 4, 16): (low=2045, high=2047), (1, 18, 4, 18): (low=2048, high=2300), (1, 20, 4, 18): (low=2301, high=2303), (1, 20, 4, 20): (low=2304, high=2556), (1, 32, 4, 20): (low=2557, high=2559), (1, 32, 4, 32): (low=2560, high=4092), (1, 37, 4, 32): (low=4093, high=4095), (1, 37, 4, 37): (low=4096, high=4735), (1, 37, 4, 64): (low=4736, high=8191), (1, 37, 4, 72): (low=8192, high=9215), (1, 37, 4, 74): (low=9216, high=163839)}
...
--------------------------------
batch_size=40
--------------------------------
len(brute_force)=19
brute_force={(40, 1, 4, 1): (low=1, high=63), (40, 1, 4, 2): (low=64, high=127), (40, 1, 4, 4): (low=128, high=4604), (40, 2, 4, 4): (low=4605, high=9212), (40, 4, 4, 4): (low=9213, high=18428), (40, 8, 4, 4): (low=18429, high=18431), (40, 8, 4, 8): (low=18432, high=36860), (40, 9, 4, 8): (low=36861, high=36863), (40, 9, 4, 9): (low=36864, high=41468), (40, 16, 4, 9): (low=41469, high=41471), (40, 16, 4, 16): (low=41472, high=73724), (40, 18, 4, 16): (low=73725, high=73727), (40, 18, 4, 18): (low=73728, high=82940), (40, 20, 4, 18): (low=82941, high=82943), (40, 20, 4, 20): (low=82944, high=92156), (40, 32, 4, 20): (low=92157, high=92159), (40, 32, 4, 32): (low=92160, high=147452), (40, 37, 4, 32): (low=147453, high=147455), (40, 37, 4, 37): (low=147456, high=163839)}
...
--------------------------------
batch_size=127
--------------------------------
len(brute_force)=19
brute_force={(127, 1, 4, 1): (low=1, high=4604), (127, 2, 4, 1): (low=4605, high=4607), (127, 2, 4, 2): (low=4608, high=9212), (127, 4, 4, 2): (low=9213, high=9215), (127, 4, 4, 4): (low=9216, high=18428), (127, 8, 4, 4): (low=18429, high=18431), (127, 8, 4, 8): (low=18432, high=36860), (127, 9, 4, 8): (low=36861, high=36863), (127, 9, 4, 9): (low=36864, high=41468), (127, 16, 4, 9): (low=41469, high=41471), (127, 16, 4, 16): (low=41472, high=73724), (127, 18, 4, 16): (low=73725, high=73727), (127, 18, 4, 18): (low=73728, high=82940), (127, 20, 4, 18): (low=82941, high=82943), (127, 20, 4, 20): (low=82944, high=92156), (127, 32, 4, 20): (low=92157, high=92159), (127, 32, 4, 32): (low=92160, high=147452), (127, 37, 4, 32): (low=147453, high=147455), (127, 37, 4, 37): (low=147456, high=163839)}
```

This means that there are 19 viable `(40, *, 4, *)` entries for
batch_size=40
and q_max_seq_len=4. The stars are num_partition and draft_num_partition
respectively.

The `(low=..., high=...)` is the range of cache_lengths that you can
probe
to achieve the given num_partition and draft_num_partition key. By
analyzing
the data for batch_sizes=1-128 and various q_max_seq_len, you can
formulate
a minimum stabbing set of cache_lengths. This ends up being something
like:

```
// minimum stabbing set via greedy (len 35)
[63, 127, 252, 255, 508, 511, 1020, 1023, 1148, 1151, 2044, 2047, 2300, 2303, 2556, 2559, 4092, 4095, 4735, 8191, 9215, 18431, 36860, 36863, 41468, 41471, 73724, 73727, 82940, 82943, 92156, 92159, 147452, 147455, 163839]
```

My heuristic of `guess = ([1] + list(range(64, 163840, 64)) +
list(range(63, 163840, 64)) + [163840])` yields a stabbing set that is a
bit larger and avoids hardcoding the above list.
```
// stabbing set via heuristic (len 5000+)
[1, 63, 64, 127, 128, ... 163840]
```

But honestly all of this cache length probing logic is wayyyyy too
complicated. We really need to redesign this so that no one needs to
understand any of it. 💀

MODULAR_ORIG_COMMIT_REV_ID: 6a3651c2b0996099d95a80a9cac47fd516824c58