[Stdlib] Add initial file I/O support to Mojo (#21983)
This adds some basic file I/O to mojo. This does not implement the full
python API (namely it does not contain readline support), but should be
enough to work with.

There are a few things that we can improve here:

- We really do not need compilerrt to do any of this, but then I did not
want to worry about linux/windows/macos differences in file handling
- The context manager in mojo seems to be weak. For exmaple I should be
able to write

```mojo
    with open(TEMP_FILE, "w") as f:
        f.write("The quick brown fox jumps over the lazy dog")
```

but that currently results in the error

```
/Users/abduld/code/modular/Kernels/test/test_file.mojo:33:14: error: use of uninitialized value 'anonymous*'
    with open(TEMP_FILE, "w") as f:
             ^
/Users/abduld/code/modular/Kernels/test/test_file.mojo:33:14: note: 'anonymous*' declared here
/Users/abduld/code/modular/Kernels/test/test_file.mojo:33:34: warning: 'f' was declared as a 'var' but never mutated, consider switching to a 'let'
    with open(TEMP_FILE, "w") as f:
                                 ^
```

due to some lifetime tracking issues

MODULAR_ORIG_COMMIT_REV_ID: 707045d13a0a428c28932f7f65847f81928d5b19