[bazel] Add All/modular unittests (#40812)
Add Bazel configs for `All/unittests/modular`.

Also move from the generic `googletest` dependency to the one vendored
in LLVM. LLVM's version contains some convenience definitions, which
fixes:

```
external/googletest~/googletest/include/gtest/gtest-message.h:148:10: error: invalid operands to binary expression ('std::stringstream' and 'const llvm::StringRef')
    *ss_ << val;
    ~~~~ ^  ~~~
```

MODULAR_ORIG_COMMIT_REV_ID: 1e1eb746af7eb615f235e4f02cedc1b3e15ff508