[KGEN] Fix missing <unordered_map> include (#51564)
In #51347, a use of `std::unordered_map` was introduced into a file that
had no `#include <unordered_map>`. This results in build failures in
some configurations:

KGEN/lib/MojoParser/Traits.cpp:33:16: error: no template named
'unordered_map' in namespace 'std'
const std::unordered_map<std::string, TypedAttr>
&aliasNameToReplacement,
              ~~~~~^
KGEN/lib/MojoParser/Traits.cpp:177:8: error: no member named
'unordered_map' in namespace 'std'
      std::unordered_map<std::string, TypedAttr> aliasNameToReplacement;
      ~~~~~^
KGEN/lib/MojoParser/Traits.cpp:177:33: error: expected '(' for
function-style cast or type construction
      std::unordered_map<std::string, TypedAttr> aliasNameToReplacement;
                         ~~~~~~~~~~~^
KGEN/lib/MojoParser/Traits.cpp:218:9: error: use of undeclared
identifier 'aliasNameToReplacement'
            aliasNameToReplacement, traitAliasReplacer);
            ^
KGEN/lib/MojoParser/Traits.cpp:279:5: error: use of undeclared
identifier 'aliasNameToReplacement'
        aliasNameToReplacement.emplace(name.str(), initializerExpr);
        ^
KGEN/lib/MojoParser/ExprEmitter.cpp:1098:16: error: no template named
'unordered_map' in namespace 'std'
const std::unordered_map<std::string, TypedAttr>
&aliasNameToReplacement,
              ~~~~~^
KGEN/lib/MojoParser/ExprEmitter.cpp:1214:8: error: no member named
'unordered_map' in namespace 'std'
      std::unordered_map<std::string, TypedAttr> aliasNameToReplacement;
      ~~~~~^
KGEN/lib/MojoParser/ExprEmitter.cpp:1214:33: error: expected '(' for
function-style cast or type construction
      std::unordered_map<std::string, TypedAttr> aliasNameToReplacement;
                         ~~~~~~~~~~~^
KGEN/lib/MojoParser/ExprEmitter.cpp:1254:7: error: use of undeclared
identifier 'aliasNameToReplacement'
          aliasNameToReplacement.emplace(name.str(), newValue);
          ^
KGEN/lib/MojoParser/ExprEmitter.cpp:1287:56: error: use of undeclared
identifier 'aliasNameToReplacement'
getContext(), typeValue, traitAliasReplacer, aliasNameToReplacement,
                                                           ^

Add the missing include to fix.

MODULAR_ORIG_COMMIT_REV_ID: a7cc7a8cdcad1e4026c771e45c43196dea81ba91