[KGEN][CheckLifetimes] Print field names when complaining about field sensitive problem (#11953)
This causes us to print errors like:
error: use of uninitialized value 'result.reg.reg1'

when only a subset of the fields are uninitialized.

MODULAR_ORIG_COMMIT_REV_ID: a5354c639cafa04ec12b088ebfebb72e7e27bdb9