Revert "[Lit] Introduce schema for value categorization. NFC." (#4089)
Reverts [Internal link]

Breaks HEAD:

```
/home/river/modular/KGEN/lib/ParseLit/LitExprs.h: In constructor 'M::KGEN::LIT::AnyValue::AnyValue(mlir::Value)':
/home/river/modular/KGEN/lib/ParseLit/LitExprs.h:88:42: error: call of overloaded 'PointerUnion(mlir::Value&)' is ambiguous
   88 |   AnyValue(Value rValue) : storage(rValue) {}
```

MODULAR_ORIG_COMMIT_REV_ID: e4216d7f81fd8ec497db3d728d8f891d0ce93f98