[modular] Fix double "http-error: " in error message (#19982)
In the case of the HTTPClient failing to reach the URL, the "http-error: " part
was getting written to `stderr` twice.  For example, before this:

```
ubuntu@ip-10-0-34-131:/mnt/modularc6i/modularml/modular$ modular install mojo
modular: error: http error: http error: failed to reach URL
/home/ubuntu/.modular/cas/0/Cq0SaiEYmcx1Th0KYGad3L3bJFLzIVkjI9vfREWbFMQ with
cURL error URL using bad/illegal format or missing URL - Looking for
Cq0SaiEYmcx1Th0KYGad3L3bJFLzIVkjI9vfREWbFMQ
```

This removes the "http error: " part from the transport error message since the
higher-level code already decorates the transport error with another "http
error: " part.  This avoids the double "http error: " in the error message shown
to users.

MODULAR_ORIG_COMMIT_REV_ID: 1bdd931cfbae2f3c6ce0a3e592d4a74a4c4e32cb