[mojo-tools] Fix a class of terrible error messages, particularly in gpu layout code
This fixes printing of parameter expression calls, which can happen in
complicated
type expressions, to include the parameter /values/ for the call and
strip off mangling
information.  On the simple testcase we would get something like:

```
invalid call to 'takes4': argument #0 cannot be converted from 'HasSize[get_int[::Int]()]' to 'HasSize[4]'
```

Now we get:

```
error: invalid call to 'takes4': argument #0 cannot be converted from 'HasSize[get_int[42]()]' to 'HasSize[4]'
    takes4(HasSize[get_int[42]()]())
          ^
```

Notice that it tells us the parameter value (`42`) instead of the type
in a verbose
form (`::Int`). While this is a minor win for this testcase, this comes
up a lot
in layout code, where one might be confronted with something useless
like:

```
invalid call to '_mha_sm90_max_prompt_len': argument #1 cannot be converted from 'TMATensorTile[KVType.dtype, tile_layout_k_major[::DType,::Int,::Int,::TensorMapSwizzle](), _tma_desc_tile_layout[::DType,::Int,::IndexList[$1, ::DType()]' to 'TMATensorTile[KVType.dtype, tile_layout_k_major[::DType,::Int,::Int,::TensorMapSwizzle](), _tma_desc_tile_layout[::DType,::Int,::IndexList[$1, ::DType()]'
```

The problem here is that the compiler is telling us exactly the wrong
thing
about `tile_layout_k_major` and `_tma_desc_tile_layout` which is both
verbose and useless.  This patch fixes this.

MODULAR_ORIG_COMMIT_REV_ID: 99284e0f32d5b2596f64be5dbcc27356deab99e8