[Eagle] Use draft model config for eagle llama3
I started seeing this error which is new :thinking:. This fixes it
```
ubuntu@workspace-bez-purple-gerbil-39-c6c7dc678-5xwjk:~/modular$ br smoke-test -- meta-llama/llama-3.1-8b-instruct__eagle
INFO: Invocation ID: d29f4456-322e-4189-949f-a705dcaa6b65
INFO: Streaming build results to: https://modular.buildbuddy.io/invocation/d29f4456-322e-4189-949f-a705dcaa6b65
INFO: Analyzed target //:smoke-test (95 packages loaded, 12886 targets configured, 3052 aspect applications).
INFO: Found 1 target...
Target //max/tests/integration/accuracy/smoke_tests:smoke_test up-to-date:
  bazel-bin/max/tests/integration/accuracy/smoke_tests/smoke_test
Aspect //bazel/pip:mypy.bzl%mypy_aspect of //:smoke-test up-to-date:
  bazel-bin/max/tests/integration/accuracy/smoke_tests/smoke_test.mypy_stdout
INFO: Elapsed time: 337.365s, Critical Path: 332.60s
INFO: 278 processes: 13139 action cache hit, 63 remote cache hit, 4 internal, 152 processwrapper-sandbox, 59 remote.
INFO: Build completed successfully, 278 total actions
INFO: Streaming build results to: https://modular.buildbuddy.io/invocation/d29f4456-322e-4189-949f-a705dcaa6b65
WARNING:__main__:No locked revision for meta-llama/Llama-3.1-8B-Instruct
INFO:__main__:Starting server with command:
 /home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_python++python+python_3_13_x86_64-unknown-linux-gnu/bin/python3 -m max.entrypoints.pipelines serve --port 8000 --trust-remote-code --model meta-llama/Llama-3.1-8B-Instruct --draft-model-path atomicapple0/EAGLE-LLaMA3.1-Instruct-8B --speculative-method eagle
20:59:06.690 INFO: Metrics initialized.
20:59:06.737 WARNING: Deprecated flag --model detected; use --model-path instead.
20:59:09.866 INFO: draft_quantization_encoding not specified, defaulting to target model encoding: bfloat16
20:59:13.985 WARNING: Prefix caching is not supported with speculative decoding. Overriding user setting to False. Pass --force to bypass this validation, though this may result in unexpected behavior or errors.
20:59:14.586 INFO:
20:59:14.586 INFO: ============================================================
20:59:14.586 INFO: Pipeline Configuration (use --pretty-print-config to print full config)
20:59:14.586 INFO: ============================================================
20:59:14.587 INFO:     model          : meta-llama/Llama-3.1-8B-Instruct
20:59:14.587 INFO:     architecture   : UnifiedEagleLlama3ForCausalLM
20:59:14.587 INFO:     pipeline       : UnifiedEAGLEPipeline
20:59:14.587 INFO:     devices        : gpu[0]
20:59:14.587 INFO:     max_batch_size : 512
20:59:14.587 INFO:     max_seq_len    : 131072
20:59:14.587 INFO:     cache_memory   : 49.16 GiB
20:59:14.587 INFO:
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/pipelines/architectures/llama3/model_config.py", line 206, in calculate_max_seq_len
    return upper_bounded_default(
        upper_bound=huggingface_config.max_position_embeddings,
        default=model_config.max_length,
    )
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/pipelines/lib/utils.py", line 154, in upper_bounded_default
    raise ValueError(
        f"default value provided ({default}) exceeds the upper bound ({upper_bound})"
    )
ValueError: default value provided (131072) exceeds the upper bound (2048)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/pipelines.py", line 546, in <module>
    main()
    ~~~~^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/pipelines.py", line 111, in invoke
    return super().invoke(ctx)
           ~~~~~~~~~~~~~~^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/cli/config.py", line 359, in wrapped
    return func(*args, **kwargs)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/cli/config.py", line 359, in wrapped
    return func(*args, **kwargs)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/cli/config.py", line 359, in wrapped
    return func(*args, **kwargs)
  [Previous line repeated 7 more times]
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/cli/config.py", line 484, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/pipelines.py", line 210, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/pipelines.py", line 304, in cli_serve
    serve_api_server_and_model_worker(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        settings=settings,
        ^^^^^^^^^^^^^^^^^^
        pipeline_config=pipeline_config,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pipeline_task=PipelineTask(task),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/entrypoints/cli/serve/serve_api_and_model_worker.py", line 76, in serve_api_server_and_model_worker
    tokenizer, pipeline_factory = PIPELINE_REGISTRY.retrieve_factory(
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        pipeline_config,
        ^^^^^^^^^^^^^^^^
        task=pipeline_task,
        ^^^^^^^^^^^^^^^^^^^
        override_architecture=override_architecture,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/pipelines/lib/registry.py", line 787, in retrieve_factory
    arch_config = arch.config.initialize(pipeline_config)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/pipelines/architectures/unified_eagle_llama3/model_config.py", line 62, in initialize
    draft_config = Llama3Config.initialize_from_config(
        pipeline_config, pipeline_config.draft_model.huggingface_config
    )
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/pipelines/architectures/llama3/model_config.py", line 343, in initialize_from_config
    max_seq_len=Llama3Config.calculate_max_seq_len(
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        pipeline_config,
        ^^^^^^^^^^^^^^^^
        huggingface_config=huggingface_config,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        model_config=model_config,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/python/max/pipelines/architectures/llama3/model_config.py", line 211, in calculate_max_seq_len
    raise ValueError(
    ...<4 lines>...
    ) from e
ValueError: Unable to infer max_length for Llama3, the provided max_length (131072) exceeds the model's max_position_embeddings (2048).
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/tests/integration/accuracy/smoke_tests/smoke_test.py", line 691, in <module>
    smoke_test()
    ~~~~~~~~~~^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/click@8.1.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/tests/integration/accuracy/smoke_tests/smoke_test.py", line 656, in smoke_test
    with start_server(cmd, timeout) as server:
         ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/external/rules_python++python+python_3_13_x86_64-unknown-linux-gnu/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/tests/integration/accuracy/smoke_tests/smoke_test.runfiles/_main/max/tests/integration/accuracy/smoke_tests/inference_server_harness.py", line 90, in start_server
    raise RuntimeError("Server process terminated unexpectedly")
RuntimeError: Server process terminated unexpectedly
```
MODULAR_ORIG_COMMIT_REV_ID: 4720bdbf2aff57640de82af1695928b5e9aabb36