Revert "[Support] Remove dependency on `MVersion` from MDialect and MSupport." (#11335)
Reverts [Internal link]

Removing this dependency as #10937 does leads to failures on clean
builds, like this:

```
In file included from /home/ubuntu/modular/Support/lib/TimeProfiler.cpp:9:
/home/ubuntu/modular/.derived/build-release/Config/include/Config/Config.h:15:10: fatal error: 'Version.h.inc' file not found
#include "Version.h.inc"
         ^~~~~~~~~~~~~~~
1 error generated.
```

MDialect also requires `Version.h.inc` in order to successfully build.
So both of these dependencies should be reintroduced.

MODULAR_ORIG_COMMIT_REV_ID: b56ba7c1cf6a49247471d07d9830ad9a35a74338