Revert "[Overlap] Automatically enable overlap scheduling for LlamaForCausalLM_Legacy, Try 2 [Internal link]
This reverts commit 957a2d23e384daebb5271452349b01d48e89c641.
This causes the following error running Llama-3.2-1B:
```python
ValueError: At max/kernels/src/linalg/matmul/gpu/__init__.mojo:1098:65: DeviceContext.enqueue_function: Dim value grid_dim.y must be a positive number.
```

Repro:
```shell
br //max -- serve --model-path meta-llama/Llama-3.2-1B --devices 0,1
```
MODULAR_ORIG_COMMIT_REV_ID: cf2b679994ea0b7a5c64c9578b4dfc2f71c7a09d