[Models] Revert "Fix Llama3 ported to ModuleV3"
Reverts
- #77529

This broke for eaxample `bartowski/Meta-Llama-3.1-8B-Instruct-GGUF-q4_k`
on intel-cpu.
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for PipelineConfig
  Value error, quantization_encoding of 'SupportedEncoding.q4_k' not supported by MAX engine.
```

MODULAR_ORIG_COMMIT_REV_ID: 402e0d0d30d51a755afee74a4dd76b9898763e50