[REPL] Print to stdout python syntax errors (#19233)
This dumps a nice error message when the ast generation fails in the
variable extraction step.
This is actually quite nice because the mojo interop doesn't show this
kind of errors.

The error that would be returned for the code in
[Internal link] is:

```
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "<string>", line 18
    let n: Int = 10_000_000
        ^
SyntaxError: invalid syntax
```

MODULAR_ORIG_COMMIT_REV_ID: 47928ea651f9fc7409762dda6e4c4596e4775423