[LLCL] Pass StringLiteral in ProfilerEntry::sample (#33235)
Explicitly pass a `StringLiteral` to `MemProfilerEntry::sample`.
Without this when enabling `Trace::kMem` I was getting the following
template instantiation error:

```text
/home/ubuntu/work/modular/Support/include/Support/Profiling/TimeProfiler.h:409:9: error: call to constructor of 'Label' is ambiguous
        name(stringArena, std::forward<NameStr>(name), nameValue) {}
```

Because there are `Label` constructors for both `StringRef` and
`std::string`, which both convert implicitly from C string literals.

MODULAR_ORIG_COMMIT_REV_ID: 64112debe7ef0d985e5e1d9642ce024a20bc1037