Revert "[Telemetry] Add getLogger() that adds fixed attributes" (#33162)
Reverts [Internal link]

Breaks local build

```
etry.dir/TelemetryContext.cpp.o -c /Users/jeff/Documents/modular/Support/lib/Telemetry/TelemetryContext.cpp
In file included from /Users/jeff/Documents/modular/Support/lib/Telemetry/TelemetryContext.cpp:7:
/Users/jeff/Documents/modular/Support/include/Support/Telemetry/Telemetry.h:245:24: error: no template named 'map' in namespace 'std'; did you mean 'max'?
            const std::map<std::string, AttributeValue> &attributes) {
                  ~~~~~^~~
                       max
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/max.h:31:1: note: 'max' declared here
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
In file included from /Users/jeff/Documents/modular/Support/lib/Telemetry/TelemetryContext.cpp:7:
/Users/jeff/Documents/modular/Support/include/Support/Telemetry/Telemetry.h:245:24: error: parameter declarator cannot be qualified
            const std::map<std::string, AttributeValue> &attributes) {
                  ~~~~~^
/Users/jeff/Documents/modular/Support/include/Support/Telemetry/Telemetry.h:245:24: error: parameter name cannot have template arguments
/Users/jeff/Documents/modular/Support/include/Support/Telemetry/Telemetry.h:245:24: error: C++ requires a type specifier for all declarations
            const std::map<std::string, AttributeValue> &attributes) {
            ~~~~~      ^
/Users/jeff/Documents/modular/Support/include/Support/Telemetry/Telemetry.h:245:57: error: expected ')'
            const std::map<std::string, AttributeValue> &attributes) {
                                                        ^
/Users/jeff/Documents/modular/Support/include/Support/Telemetry/Telemetry.h:244:12: note: to match this '('
  getLogger(StringRef eventDomain,
           ^
5 errors generated.
ninja: build stopped: subcommand failed.
```

MODULAR_ORIG_COMMIT_REV_ID: d575b477d065270dd5a3a5b9102cf9d5b5f889df