[NFC] Fix missing MSupport LINK_LIBS for MSupportDriver. (#16485)
Build complained about `undefined reference to
M::Error::Error(llvm::Twine)`

MODULAR_ORIG_COMMIT_REV_ID: 0d0ae62dd0c7e92c30f60d75d7de256579115c57