[REPL] Work around a flake in a test (#42255)
This test has flaked a few times. Some times the REPL outputs

```
Error: oopsy woopsy
Unhandled exception caught during execution
```

and sometimes it outputs

```
Error: Unhandled exception caught during execution
oopsy woopsy
```

The first variant is way more frequent. The reason of this issue is a
race condition when processing all input streams within the REPL. An
easy way to work around this is simply to avoid checking for the `Error:
` substring.

MODULAR_ORIG_COMMIT_REV_ID: e4ac00ac8aaf06da601daf503a43669e85724af0