[CI] Add error reporting to max/python/max/_interpreter.py On the AMD MI355 we need to get more output to see what is causing this error in CI, ImportError: cannot import name 'MOInterpreter' from 'max._interpreter'
MODULAR_ORIG_COMMIT_REV_ID: e693233b1329ac2acd0806528fccc54844a98702