[Serve] Revert "[Serve] Move pool_embeddings from PipelineConfig to MAXModelConfig"
Reverts [Internal link] as it broke
logit
verification for mpnet.

```
./bazelw run --config=disable-lint -- //max/tests/integration/tools:generate_llm_logits --framework max --pipeline sentence-transformers/all-mpnet-base-v2 --device cpu --output /tmp/output.json
```

Due to this commit, the outputs are `"shape": [768]` instead of the
expected `"shape": [28, 768]`

This causes a shape mismatch error

```
  File "/github/home/.cache/bazel/_bazel_root/991c1318309cea4e3284840cbcc05428/execroot/_main/bazel-out/k8-opt-ci-build/bin/max/tests/integration/accuracy/verify_pipelines.runfiles/_main/max/tests/integration/test_common/verify_utils.py", line 1103, in _is_close
    result[~finite] = a[~finite] == b[~finite]
                      ~^^^^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

[Internal link]

MODULAR_ORIG_COMMIT_REV_ID: 4fa06bda8df5c7916f8d01649c50c769b7447075