[Build] Fix symlinking logic when switching between build profiles (#19780)
When I switch between build profiles in local environment, e.g. first
`cmake-modular-release && build && install ...` then
`cmake-modular-relwithdebinfo`, I get the following error during cmake
config:
```
Traceback (most recent call last):
  File "/mnt/modularc6i/modularml/modular/utils/build.py", line 1268, in <module>
    main()
  File "/mnt/modularc6i/modularml/modular/utils/build.py", line 1251, in main
    link_build_dir(
  File "/mnt/modularc6i/modularml/modular/utils/build.py", line 1008, in link_build_dir
    link_modular_config(true_build_dir / "modular.cfg")
  File "/mnt/modularc6i/modularml/modular/utils/build.py", line 994, in link_modular_config
    create_symlink(DERIVED_DIRECTORY / "modular.cfg", config_path)
  File "/mnt/modularc6i/modularml/modular/Support/python/modular/utils/misc/_misc.py", line 81, in create_symlink
    destination.symlink_to(src, target_is_directory)
  File "/usr/lib/python3.8/pathlib.py", line 1384, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/usr/lib/python3.8/pathlib.py", line 446, in symlink
    return os.symlink(a, b)
FileExistsError: [Errno 17] File exists: '/mnt/modularc6i/modularml/modular/.derived/build-relwithdebinfo/modular.cfg' -> '/mnt/modularc6i/modularml/modular/.derived/modular.cfg'
```

This happens because
`/mnt/modularc6i/modularml/modular/.derived/modular.cfg` symlink is left
dangling and points to a non-existent file. For those broken symlinks
`path.exists()` returns False as per [the
documentation](https://docs.python.org/3/library/os.path.html#os.path.exists)
To fix that we also check if the destination is a symlink.

MODULAR_ORIG_COMMIT_REV_ID: 8b4a5e8ab67127e5fe877774c11f33028d3d057a