[stdlib] Replace most uses of `__get_lvalue_as_address` with `Reference` (#2035) (#36428)
Replace most uses of `__get_lvalue_as_address` with `Reference`. The two
remaining uses at `memory/anypointer.mojo` and `memory/unsafe.mojo`
can't switch over to using `Reference` since register passable things don't carry a
lifetime value (and thus cannot be used with `Reference`). They are current
rejected by the compiler with the error:

```mojo
error: cannot form a reference to an argument that might instantiate to
@register_passable type
```

modular-orig-commit: ff7e21a5cbee8c3359fa63fa6f8049690f051653