[MAX] Fix import in smoke-test
Whoops, I broke it.

Orig error:
```
  File "/home/runner/_work/modular/modular/max/tests/integration/accuracy/smoke_tests/smoke_test.py", line 61, in <module>
    from max.nn.kv_cache import KVConnectorType
ModuleNotFoundError: No module named 'max'
```
MODULAR_ORIG_COMMIT_REV_ID: bdc750c1189667bfce79591fd31f3c4a82df4e38