[DeviceContext] Improve invalid CUDA driver error (#54040)
Check for the correct version of the CUDA driver that is installed and
provide a useful error message to the user if the version is not
compatible with MAX. An example of an error message the user might see
from the Python Graph API is:

```
ValueError: failed to create device: MAX is not supported using current
GPU driver. Use at least NVIDIA driver version 555 and CUDA version
12.5. Use the nvidia-smi command to check the current NVIDIA driver and
CUDA versions installed. The current CUDA version MAX detected is: 12.3
```

Currently MAX requires NVIDIA driver version 555, which corresponds to
CUDA version 12.5.

To implement this change, the way the CUDA version is handled from the
`cuDriverGetVersion` method had to change. Previously the code did not
correctly handle the value returned from that method.

In addition, this change adds a Python test to the Driver device
accelerator tests to validate the CUDA version via the
`is_compatible_with_max` API added in
[Internal link] This should help local
developers validate that they have the proper driver versions installed.

Note that we already

[Internal link]
NVIDIA driver version 555 is required. This change allows MAX to
validate that requirement at run time.

Fixes GEX-1618

---------

Co-authored-by: abdul dakkak <adakkak@modular.com>
Co-authored-by: Scott Main <scott@modular.com>
MAX_TESTS_TESTS_ORIG_REV_ID: f5c2fa9977ecd6424f610c046ec65e421d4d8342