[CI] [Pipelines] Fix weight_path PosixPath error in generate_llm_logits (#51312)
Fixes this error:

File "SDK/lib/API/python/max/pipelines/tokenizer.py", line 120, in
__init__
if len(config.weight_path) == 0 and config.huggingface_repo_id is None:
           ^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: object of type 'PosixPath' has no len()

Also turns MyPy on again since we're no longer blocked -- would have
caught this problem ahead of time.

MAX_INTEGRATION_TESTS_REV_ID: 391452651d47aceaf20ff30a961cf430236ad86b