[mojo-driver] Fix options enum redefinition (#16263)
When run under UBSan, the `mojo-driver doc` tests fail:

```
modular/third-party/llvm-project/llvm/include/llvm/Option/ArgList.h:245:23: runtime error: load of value 10, which is not a valid value for type 'options::ID'
    #0 0x10043ed68 in bool llvm::opt::ArgList::hasArg<options::ID>(options::ID) const ArgList.h:245
    #1 0x1004751d4 in doc(M::State const&) mojo-doc.cpp:111
    #2 0x1004745b8 in decltype(std::declval<int (*&)(M::State const&)>()(std::declval<M::State const&>())) std::__1::__invoke[abi:v15006]<int (*&)(M::State const&), M::State const&>(int (*&)(M::State const&), M::State const&) invoke.h:394
    #3 0x1004743e4 in int std::__1::__invoke_void_return_wrapper<int, false>::__call<int (*&)(M::State const&), M::State const&>(int (*&)(M::State const&), M::State const&) invoke.h:470
    #4 0x100474330 in std::__1::__function::__alloc_func<int (*)(M::State const&), std::__1::allocator<int (*)(M::State const&)>, int (M::State const&)>::operator()[abi:v15006](M::State const&) function.h:185
    #5 0x1004706bc in std::__1::__function::__func<int (*)(M::State const&), std::__1::allocator<int (*)(M::State const&)>, int (M::State const&)>::operator()(M::State const&) function.h:359
    #6 0x10043bb44 in std::__1::__function::__value_func<int (M::State const&)>::operator()[abi:v15006](M::State const&) const function.h:512
    #7 0x100419a34 in std::__1::function<int (M::State const&)>::operator()(M::State const&) const function.h:1197
    #8 0x100418280 in main mojo-driver.cpp:163
    #9 0x184917f24  (<unknown module>)
```

This error message seems wrong, because there are actually 11 `OPTION`
definitions in the x-macros emitted to `Doc/DocOptions.inc`. However,
the trouble lies in the fact that each driver subcommand includes
`OptTable.inc `, which defines the `enum ID` in the same `options`
namespace.

You'll see the same pattern in other LLVM projects that use LLVMOption,
like in the Clang project. However, those projects define *all* of their
options in a *single* file, so they only define a single
`namespace options { enum ID { ... }; }` across their translation units.

It seems obvious now, but because these mojo-driver subcommands each
define `namespace options { enum ID { ... }; }`, it violates the One
Definition Rule -- multiple definitions of `options::ID` exist in the
`mojo-driver` program.

Especially considering these enumerators are populated with an x-macro
generated by TableGen, I wish to continue scoping them in each
subcommand implementation file (so that users must write
`options::OPT_INPUT` instead of just `OPT_INPUT`). And, since the
convention in other LLVM projects to do so is to use a `enum ID`, but
within a named namespace like `options`, I wish to keep that the same as
well. But, to avoid ODR violations, place each of these namespaces
within another anonymous namespace. This prevents ODR violations and
fixes all UBSan errors in the mojo-driver and mojo-tblgen tests.

MODULAR_ORIG_COMMIT_REV_ID: f88c43400c31f4058368d72f0c3067ace2596087